[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  GMAP_API_KEY = "GMAP_API_KEY"
  FIREBASE_API_KEY = "FIREBASE_API_KEY"
  FIREBASE_AUTH_DOMAIN = "FIREBASE_AUTH_DOMAIN"
  FIREBASE_PROJECT_ID = "FIREBASE_PROJECT_ID"
  FIREBASE_DATABASE_URL = "FIREBASE_DATABASE_URL"
  FIREBASE_STORAGE_BUCKET = "FIREBASE_STORAGE_BUCKET"
  FIREBASE_MESSAGE_SENDER_ID = "FIREBASE_MESSAGE_SENDER_ID"
  FIREBASE_APP_ID = "FIREBASE_APP_ID"
